# ============================================================
# YAML ANCHORS (must be outside the blueprint block)
# ============================================================
button_options: &button_options
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
action_type_options: &action_type_options
  - single
  - double
  - hold
  - long
  - release
  - custom

# ============================================================
# BLUEPRINT
# ============================================================

blueprint:
  name: Zigbee2MQTT – Generic Action Mapper (Pattern + 12 slots)
  description: >
    A generic blueprint for mapping Zigbee2MQTT action payloads to Home Assistant actions.
    The action name is constructed from a user-defined pattern using {{button}} and {{type}}.
  domain: automation

  # version: 1.3.1

  input:

    # -----------------------------
    # DEVICE + PATTERN
    # -----------------------------

    device_name:
      name: Zigbee2MQTT Device Name
      description: Must match zigbee2mqtt/<name>/action
      selector:
        device:
          integration: mqtt

    action_pattern:
      name: Action Pattern
      description: >
        Use {{button}} and {{type}} placeholders.
        Example: "{{button}}_{{type}}" or "button_{{button}}_{{type}}"
      default: "{{button}}_{{type}}"
      selector:
        text:

    # ============================================================
    # 12 MAPPING SLOTS (OPTIONAL)
    # ============================================================

    # SLOT 1
    mapping_1_button:
      name: Mapping 1 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_1_type:
      name: Mapping 1 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_1_type_custom:
      name: Mapping 1 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_1_ha_action:
      name: Mapping 1 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 2
    mapping_2_button:
      name: Mapping 2 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_2_type:
      name: Mapping 2 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_2_type_custom:
      name: Mapping 2 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_2_ha_action:
      name: Mapping 2 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 3
    mapping_3_button:
      name: Mapping 3 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_3_type:
      name: Mapping 3 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_3_type_custom:
      name: Mapping 3 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_3_ha_action:
      name: Mapping 3 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 4
    mapping_4_button:
      name: Mapping 4 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_4_type:
      name: Mapping 4 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_4_type_custom:
      name: Mapping 4 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_4_ha_action:
      name: Mapping 4 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 5
    mapping_5_button:
      name: Mapping 5 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_5_type:
      name: Mapping 5 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_5_type_custom:
      name: Mapping 5 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_5_ha_action:
      name: Mapping 5 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 6
    mapping_6_button:
      name: Mapping 6 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_6_type:
      name: Mapping 6 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_6_type_custom:
      name: Mapping 6 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_6_ha_action:
      name: Mapping 6 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 7
    mapping_7_button:
      name: Mapping 7 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_7_type:
      name: Mapping 7 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_7_type_custom:
      name: Mapping 7 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_7_ha_action:
      name: Mapping 7 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 8
    mapping_8_button:
      name: Mapping 8 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_8_type:
      name: Mapping 8 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_8_type_custom:
      name: Mapping 8 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_8_ha_action:
      name: Mapping 8 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 9
    mapping_9_button:
      name: Mapping 9 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_9_type:
      name: Mapping 9 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_9_type_custom:
      name: Mapping 9 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_9_ha_action:
      name: Mapping 9 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 10
    mapping_10_button:
      name: Mapping 10 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_10_type:
      name: Mapping 10 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_10_type_custom:
      name: Mapping 10 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_10_ha_action:
      name: Mapping 10 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 11
    mapping_11_button:
      name: Mapping 11 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_11_type:
      name: Mapping 11 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_11_type_custom:
      name: Mapping 11 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_11_ha_action:
      name: Mapping 11 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 12
    mapping_12_button:
      name: Mapping 12 – Button Number
      selector:
        select:
          options: *button_options
      default: ""

    mapping_12_type:
      name: Mapping 12 – Action Type
      selector:
        select:
          options: *action_type_options
      default: ""

    mapping_12_type_custom:
      name: Mapping 12 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_12_ha_action:
      name: Mapping 12 – Home Assistant Action
      selector:
        action:
      default: []

# ============================================================
# TRIGGER
# ============================================================

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device_name }}/action"

# ============================================================
# VARIABLES
# ============================================================

variables:
  payload: "{{ trigger.payload }}"
  pattern: !input action_pattern

  mappings:
    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_1_button | string))
            | replace("{{type}}", (
                !input mapping_1_type == "custom"
                and !input mapping_1_type_custom
                or !input mapping_1_type
              ) | string)
        }}
      ha: !input mapping_1_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_2_button | string))
            | replace("{{type}}", (
                !input mapping_2_type == "custom"
                and !input mapping_2_type_custom
                or !input mapping_2_type
              ) | string)
        }}
      ha: !input mapping_2_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_3_button | string))
            | replace("{{type}}", (
                !input mapping_3_type == "custom"
                and !input mapping_3_type_custom
                or !input mapping_3_type
              ) | string)
        }}
      ha: !input mapping_3_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_4_button | string))
            | replace("{{type}}", (
                !input mapping_4_type == "custom"
                and !input mapping_4_type_custom
                or !input mapping_4_type
              ) | string)
        }}
      ha: !input mapping_4_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_5_button | string))
            | replace("{{type}}", (
                !input mapping_5_type == "custom"
                and !input mapping_5_type_custom
                or !input mapping_5_type
              ) | string)
        }}
      ha: !input mapping_5_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_6_button | string))
            | replace("{{type}}", (
                !input mapping_6_type == "custom"
                and !input mapping_6_type_custom
                or !input mapping_6_type
              ) | string)
        }}
      ha: !input mapping_6_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_7_button | string))
            | replace("{{type}}", (
                !input mapping_7_type == "custom"
                and !input mapping_7_type_custom
                or !input mapping_7_type
              ) | string)
        }}
      ha: !input mapping_7_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_8_button | string))
            | replace("{{type}}", (
                !input mapping_8_type == "custom"
                and !input mapping_8_type_custom
                or !input mapping_8_type
              ) | string)
        }}
      ha: !input mapping_8_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_9_button | string))
            | replace("{{type}}", (
                !input mapping_9_type == "custom"
                and !input mapping_9_type_custom
                or !input mapping_9_type
              ) | string)
        }}
      ha: !input mapping_9_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_10_button | string))
            | replace("{{type}}", (
                !input mapping_10_type == "custom"
                and !input mapping_10_type_custom
                or !input mapping_10_type
              ) | string)
        }}
      ha: !input mapping_10_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_11_button | string))
            | replace("{{type}}", (
                !input mapping_11_type == "custom"
                and !input mapping_11_type_custom
                or !input mapping_11_type
              ) | string)
        }}
      ha: !input mapping_11_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_12_button | string))
            | replace("{{type}}", (
                !input mapping_12_type == "custom"
                and !input mapping_12_type_custom
                or !input mapping_12_type
              ) | string)
        }}
      ha: !input mapping_12_ha_action

# ============================================================
# ACTION
# ============================================================

action:
  - choose:
      - conditions: "{{ payload == mappings[0].action }}"
        sequence: !input mapping_1_ha_action

      - conditions: "{{ payload == mappings[1].action }}"
        sequence: !input mapping_2_ha_action

      - conditions: "{{ payload == mappings[2].action }}"
        sequence: !input mapping_3_ha_action

      - conditions: "{{ payload == mappings[3].action }}"
        sequence: !input mapping_4_ha_action

      - conditions: "{{ payload == mappings[4].action }}"
        sequence: !input mapping_5_ha_action

      - conditions: "{{ payload == mappings[5].action }}"
        sequence: !input mapping_6_ha_action

      - conditions: "{{ payload == mappings[6].action }}"
        sequence: !input mapping_7_ha_action

      - conditions: "{{ payload == mappings[7].action }}"
        sequence: !input mapping_8_ha_action

      - conditions: "{{ payload == mappings[8].action }}"
        sequence: !input mapping_9_ha_action

      - conditions: "{{ payload == mappings[9].action }}"
        sequence: !input mapping_10_ha_action

      - conditions: "{{ payload == mappings[10].action }}"
        sequence: !input mapping_11_ha_action

      - conditions: "{{ payload == mappings[11].action }}"
        sequence: !input mapping_12_ha_action

mode: single
