
# ============================================================
# BLUEPRINT
# ============================================================

blueprint:
  name: Zigbee2MQTTT
  description: >
    A generic blueprint for mapping Zigbee2MQTT action payloads to Home Assistant actions.
    
  domain: automation
  version: "1.2.10"

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device_name }}/action"

# ============================================================
# VARIABLES
# ============================================================

variables:
  payload: "{{ trigger.payload }}"
  pattern: !input action_pattern

  

# ============================================================
# ACTION
# ============================================================

action:
  - choose:
      - conditions: "{{ payload in mappings | map(attribute='action') | list }}"
        sequence:
          - variables:
              idx: "{{ (mappings | map(attribute='action') | list).index(payload) }}"
              selected: "{{ mappings[idx].ha }}"
          - choose:
              - conditions: "{{ selected is defined }}"
                sequence: !input selected

mode: single
