# -----------------------------
# YAML ANCHORS (must be outside blueprint)
# -----------------------------

button_options: &button_options
  - "1"
  - "2"
  - "3"
  - "4"

action_type_options: &action_type_options
  - single
  - double
  - hold
  - long
  - release
  - custom

# -----------------------------
# BLUEPRINT HEADER
# -----------------------------

blueprint:
  name: Zigbee2MQTT – Generic Action Mapper (Pattern + Anchors)
  description: >
    A generic blueprint for mapping Zigbee2MQTT action payloads.
  domain: automation
  version: "1.2.0"

  input:

    device_name:
      name: Zigbee2MQTT Device Name
      selector:
        text:

    action_pattern:
      name: Action Pattern
      default: "{{button}}_{{type}}"
      selector:
        text:

    # SLOT 1
    mapping_1_button:
      name: Mapping 1 – Button Number
      selector:
        select:
          options: *button_options

    mapping_1_type:
      name: Mapping 1 – Action Type
      selector:
        select:
          options: *action_type_options

    mapping_1_type_custom:
      name: Mapping 1 – Custom Action Type
      selector:
        text:

    mapping_1_ha_action:
      name: Mapping 1 – Home Assistant Action
      selector:
        action:

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device_name }}/action"

variables:
  payload: "{{ trigger.payload }}"
  pattern: !input action_pattern

  mappings:
    - action: >
        {{ pattern
            | replace("{{button}}", (!input mapping_1_button | string))
            | replace("{{type}}", (
                !input mapping_1_type == "custom"
                and !input mapping_1_type_custom
                or !input mapping_1_type
              ) | string)
        }}
      ha: !input mapping_1_ha_action

action:
  - choose:
      - conditions: "{{ payload == mappings[0].action }}"
        sequence: !input mapping_1_ha_action

mode: single
