blueprint:
  name: Zigbee2MQTT – Generic Action Mapper (Pattern + 12 slots)
  description: >
    A generic blueprint for mapping Zigbee2MQTT action payloads to Home Assistant actions.
    The action name is constructed from a user-defined pattern using {{button}} and {{type}}.
    Version 1.3.4
  domain: automation

  input:

    # -----------------------------
    # DEVICE + PATTERN
    # -----------------------------

    device_name:
      name: Zigbee2MQTT Device
      description: Select the MQTT device that publishes zigbee2mqtt/<name>/action
      selector:
        device:
          integration: mqtt

    action_pattern:
      name: Action Pattern
      description: >
        Use {{button}} and {{type}} placeholders.
        Example: "{{button}}_{{type}}" or "button_{{button}}_{{type}}"
      default: "{{button}}_{{type}}"
      selector:
        text:

    # ============================================================
    # 12 MAPPING SLOTS (OPTIONAL)
    # ============================================================

    # SLOT 1
    mapping_1_button:
      name: Mapping 1 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_1_type:
      name: Mapping 1 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_1_type_custom:
      name: Mapping 1 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_1_ha_action:
      name: Mapping 1 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 2
    mapping_2_button:
      name: Mapping 2 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_2_type:
      name: Mapping 2 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_2_type_custom:
      name: Mapping 2 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_2_ha_action:
      name: Mapping 2 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 3
    mapping_3_button:
      name: Mapping 3 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_3_type:
      name: Mapping 3 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_3_type_custom:
      name: Mapping 3 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_3_ha_action:
      name: Mapping 3 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 4
    mapping_4_button:
      name: Mapping 4 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_4_type:
      name: Mapping 4 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_4_type_custom:
      name: Mapping 4 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_4_ha_action:
      name: Mapping 4 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 5
    mapping_5_button:
      name: Mapping 5 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_5_type:
      name: Mapping 5 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_5_type_custom:
      name: Mapping 5 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_5_ha_action:
      name: Mapping 5 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 6
    mapping_6_button:
      name: Mapping 6 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_6_type:
      name: Mapping 6 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_6_type_custom:
      name: Mapping 6 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_6_ha_action:
      name: Mapping 6 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 7
    mapping_7_button:
      name: Mapping 7 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_7_type:
      name: Mapping 7 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_7_type_custom:
      name: Mapping 7 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_7_ha_action:
      name: Mapping 7 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 8
    mapping_8_button:
      name: Mapping 8 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_8_type:
      name: Mapping 8 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_8_type_custom:
      name: Mapping 8 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_8_ha_action:
      name: Mapping 8 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 9
    mapping_9_button:
      name: Mapping 9 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_9_type:
      name: Mapping 9 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_9_type_custom:
      name: Mapping 9 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_9_ha_action:
      name: Mapping 9 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 10
    mapping_10_button:
      name: Mapping 10 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_10_type:
      name: Mapping 10 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_10_type_custom:
      name: Mapping 10 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_10_ha_action:
      name: Mapping 10 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 11
    mapping_11_button:
      name: Mapping 11 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_11_type:
      name: Mapping 11 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_11_type_custom:
      name: Mapping 11 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_11_ha_action:
      name: Mapping 11 – Home Assistant Action
      selector:
        action:
      default: []

    # SLOT 12
    mapping_12_button:
      name: Mapping 12 – Button Number
      selector:
        select:
          options: ["1","2","3","4","5","6","7","8","9"]
      default: ""

    mapping_12_type:
      name: Mapping 12 – Action Type
      selector:
        select:
          options: ["single","double","hold","long","release","custom"]
      default: ""

    mapping_12_type_custom:
      name: Mapping 12 – Custom Action Type
      selector:
        text:
      default: ""

    mapping_12_ha_action:
      name: Mapping 12 – Home Assistant Action
      selector:
        action:
      default: []

# ============================================================
# TRIGGER
# ============================================================

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device_name }}/action"

# ============================================================
# VARIABLES
# ============================================================

variables:
  payload: "{{ trigger.payload }}"
  pattern: !input action_pattern

  # Extract all inputs into plain variables
  b1: !input mapping_1_button
  t1: !input mapping_1_type
  tc1: !input mapping_1_type_custom

  b2: !input mapping_2_button
  t2: !input mapping_2_type
  tc2: !input mapping_2_type_custom

  b3: !input mapping_3_button
  t3: !input mapping_3_type
  tc3: !input mapping_3_type_custom

  b4: !input mapping_4_button
  t4: !input mapping_4_type
  tc4: !input mapping_4_type_custom

  b5: !input mapping_5_button
  t5: !input mapping_5_type
  tc5: !input mapping_5_type_custom

  b6: !input mapping_6_button
  t6: !input mapping_6_type
  tc6: !input mapping_6_type_custom

  b7: !input mapping_7_button
  t7: !input mapping_7_type
  tc7: !input mapping_7_type_custom

  b8: !input mapping_8_button
  t8: !input mapping_8_type
  tc8: !input mapping_8_type_custom

  b9: !input mapping_9_button
  t9: !input mapping_9_type
  tc9: !input mapping_9_type_custom

  b10: !input mapping_10_button
  t10: !input mapping_10_type
  tc10: !input mapping_10_type_custom

  b11: !input mapping_11_button
  t11: !input mapping_11_type
  tc11: !input mapping_11_type_custom

  b12: !input mapping_12_button
  t12: !input mapping_12_type
  tc12: !input mapping_12_type_custom

  # Build mapping table using only variables (no !input inside templates)
  mappings:
    - action: >
        {{ pattern
            | replace("{{button}}", b1)
            | replace("{{type}}", (tc1 if t1 == "custom" else t1))
        }}
      ha: !input mapping_1_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b2)
            | replace("{{type}}", (tc2 if t2 == "custom" else t2))
        }}
      ha: !input mapping_2_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b3)
            | replace("{{type}}", (tc3 if t3 == "custom" else t3))
        }}
      ha: !input mapping_3_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b4)
            | replace("{{type}}", (tc4 if t4 == "custom" else t4))
        }}
      ha: !input mapping_4_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b5)
            | replace("{{type}}", (tc5 if t5 == "custom" else t5))
        }}
      ha: !input mapping_5_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b6)
            | replace("{{type}}", (tc6 if t6 == "custom" else t6))
        }}
      ha: !input mapping_6_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b7)
            | replace("{{type}}", (tc7 if t7 == "custom" else t7))
        }}
      ha: !input mapping_7_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b8)
            | replace("{{type}}", (tc8 if t8 == "custom" else t8))
        }}
      ha: !input mapping_8_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b9)
            | replace("{{type}}", (tc9 if t9 == "custom" else t9))
        }}
      ha: !input mapping_9_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b10)
            | replace("{{type}}", (tc10 if t10 == "custom" else t10))
        }}
      ha: !input mapping_10_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b11)
            | replace("{{type}}", (tc11 if t11 == "custom" else t11))
        }}
      ha: !input mapping_11_ha_action

    - action: >
        {{ pattern
            | replace("{{button}}", b12)
            | replace("{{type}}", (tc12 if t12 == "custom" else t12))
        }}
      ha: !input mapping_12_ha_action

# ============================================================
# ACTION
# ============================================================

action:
  - choose:
      - conditions: "{{ payload == mappings[0].action }}"
        sequence: !input mapping_1_ha_action

      - conditions: "{{ payload == mappings[1].action }}"
        sequence: !input mapping_2_ha_action

      - conditions: "{{ payload == mappings[2].action }}"
        sequence: !input mapping_3_ha_action

      - conditions: "{{ payload == mappings[3].action }}"
        sequence: !input mapping_4_ha_action

      - conditions: "{{ payload == mappings[4].action }}"
        sequence: !input mapping_5_ha_action

      - conditions: "{{ payload == mappings[5].action }}"
        sequence: !input mapping_6_ha_action

      - conditions: "{{ payload == mappings[6].action }}"
        sequence: !input mapping_7_ha_action

      - conditions: "{{ payload == mappings[7].action }}"
        sequence: !input mapping_8_ha_action

      - conditions: "{{ payload == mappings[8].action }}"
        sequence: !input mapping_9_ha_action

      - conditions: "{{ payload == mappings[9].action }}"
        sequence: !input mapping_10_ha_action

      - conditions: "{{ payload == mappings[10].action }}"
        sequence: !input mapping_11_ha_action

      - conditions: "{{ payload == mappings[11].action }}"
        sequence: !input mapping_12_ha_action

mode: single
